# Generated by Django 3.2.9 on 2022-02-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='board.Attachment'),
        ),
    ]
